const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Anchor,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Dictionary,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Behaviors.Fade,
		C3.Behaviors.MoveTo,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.SVGPicture,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Cnds.IsEmpty,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Audio.Acts.SetVolume
	];
};
self.C3_JsPropNameTable = [
	{Awan1: 0},
	{Awan2: 0},
	{Awan3: 0},
	{Sine: 0},
	{AwanRumah: 0},
	{BG_RoadMap: 0},
	{BG_RoadMap2: 0},
	{BTN_1: 0},
	{BTN_10: 0},
	{TargetLayout: 0},
	{BTN_11: 0},
	{BTN_12: 0},
	{BTN_13: 0},
	{BTN_14: 0},
	{BTN_15: 0},
	{BTN_2: 0},
	{BTN_3: 0},
	{BTN_4: 0},
	{BTN_5: 0},
	{BTN_6: 0},
	{BTN_7: 0},
	{BTN_8: 0},
	{BTN_9: 0},
	{BTN_MusicOff: 0},
	{BTN_MusicOn: 0},
	{BTN_SoundOff: 0},
	{BTN_SoundOn: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{CameraFocus: 0},
	{PulauKamarTidur: 0},
	{PulauKebunBinatang: 0},
	{PulauKelas: 0},
	{Anchor: 0},
	{MainTitle: 0},
	{Numa: 0},
	{Numi: 0},
	{StartButton: 0},
	{BG_MainMenu: 0},
	{Group: 0},
	{Drop: 0},
	{PostX: 0},
	{PostY: 0},
	{SizeX: 0},
	{SizeY: 0},
	{DragDrop: 0},
	{Tween: 0},
	{Drag: 0},
	{Banner: 0},
	{Tema_KamarTidurLV1TKB: 0},
	{Sprite: 0},
	{Drag_2: 0},
	{Drop_2: 0},
	{Bg_Lvl1_Open: 0},
	{Bg_Level2_T2: 0},
	{Drag_Lvl2: 0},
	{Bg_Level2_Open: 0},
	{Drop_Lvl2: 0},
	{Bg_lvl3_Basic_PA: 0},
	{Btn_Lvl3_Play: 0},
	{Answer: 0},
	{isClickable: 0},
	{Angka_lvl3_PA: 0},
	{Bg_Lvl4_Basic_PA: 0},
	{Judul_Lvl4_PA: 0},
	{Btn_Play_Lvl4_Basic_PA: 0},
	{Karakter_Lvl4_Basic_PA: 0},
	{Drag_Lvl4_PA: 0},
	{Papan_Lvl4_PA: 0},
	{Buku_Lvl4_PA: 0},
	{Judul_Lvl4_PA_Game: 0},
	{Drop_Lvl4_PA: 0},
	{LEMARI_lVL4_pa: 0},
	{Dialog_Lvl4_PA: 0},
	{Target_Lay_Buku: 0},
	{Drag_Buku_Lvl4_PA: 0},
	{Drop_Buku_Lvl4_PA: 0},
	{Btn_Back_Lvl4_PA: 0},
	{Kartu_Buku_Lvl4_PA: 0},
	{DataLevel4_PA: 0},
	{Sprite6: 0},
	{Bayangan_Lvl4_PA: 0},
	{JudulBuku_Lvl4_PA: 0},
	{Bg_Lvl5_PA: 0},
	{SIzeX: 0},
	{Play_BTN_Lvl5_PA: 0},
	{Drag_Lvl5_PA: 0},
	{Dialog_Lvl5_PA: 0},
	{Lanjut_Lvl5_PA: 0},
	{Header_Lvl5_PA: 0},
	{Drop_Lvl5_PA: 0},
	{Btb_Play_Lvl7: 0},
	{Group3: 0},
	{sizeX: 0},
	{isClick: 0},
	{bebek_lvl7: 0},
	{Sprite3: 0},
	{BTN_Play_Lvl7: 0},
	{aNGKA_Lvl7_PA: 0},
	{postX: 0},
	{Drag_Bubble_Lvl8_PA: 0},
	{Bg_Lvl8_PA: 0},
	{Asset_Lvl8_PA: 0},
	{Btn_Play_Lvl8_PA: 0},
	{Drop_Bubble_Lvl8_PA: 0},
	{checklist_lvl9_PA: 0},
	{bebek_lvl9_PA: 0},
	{Text_Lvl9_PA: 0},
	{BubbleClr_Lvl9_PA: 0},
	{answer: 0},
	{Bubble_Lvl9_PA: 0},
	{Number_Level9_PA: 0},
	{bg_Lvl9_PA: 0},
	{bgfull_Lvl9_PA: 0},
	{bgfix_Lvl9_PA: 0},
	{BtnPlay_Lvl9_PA: 0},
	{Bg_Lvl10_PA: 0},
	{Btn_Play_Lvl10: 0},
	{DragSabun_Lvl10_PA: 0},
	{DropSabun_Lvl10_PA: 0},
	{Bg_Lvl6_PA: 0},
	{Btn_Play_Lvl6_PA: 0},
	{NilaiAngka: 0},
	{SudahDiinjak: 0},
	{Lantai_Lvl6_PA: 0},
	{LantaiBenar_Lvl6_PA: 0},
	{Numi_Lvl6_PA: 0},
	{Nyawa_Lvl6_PA: 0},
	{NyawaText_Lvl6_PA: 0},
	{Bg_Lvl14_PA: 0},
	{Drag_Card_Lvl14_PA: 0},
	{Btn_Play_Lvl14_Pa: 0},
	{Btn_Next_Lvl14_PA: 0},
	{Drop_Card_Lvl14_PA2: 0},
	{Asset_Lvl11: 0},
	{BG_Lvl11: 0},
	{Btn_Play_Lvl11_PA: 0},
	{Id_Angka: 0},
	{isFlipped: 0},
	{isMatched: 0},
	{Card_Lvl11_PA: 0},
	{Text_Lvl11: 0},
	{Btn_Next_Lvl15_PA: 0},
	{ID_Number: 0},
	{Card_Lvl15_PA: 0},
	{Bg_Lvl15_PA: 0},
	{Asset_Lvl15_PA: 0},
	{Btn_Play_Lvl15_PA: 0},
	{Sprite5: 0},
	{ShowCard_Lvl15_PA2: 0},
	{NextShowCard_Lvl15_PA3: 0},
	{Karakter_Lvl15_PA: 0},
	{Text_Finish_Lvl15PA: 0},
	{Chanel_Lvl12_PA: 0},
	{Btn_Play_Lvl12_PA: 0},
	{AngkaRemote_Lvl12_PA: 0},
	{ChatNumi_Lvl12_PA: 0},
	{ChatNuma_Lvl12_PA: 0},
	{Asset_Lvl12_PA: 0},
	{Bg_Lvl12_PA: 0},
	{TextPuluhan_Lvl12_PA: 0},
	{TextSatuan_Lvl12_PA: 0},
	{AngkaAcak: 0},
	{anima: 0},
	{UntitledDesign: 0},
	{Lanjut_Lvl12_PA: 0},
	{BalokSatuan_Lvl13_PA: 0},
	{Id_Puluhan: 0},
	{Id_Satuan: 0},
	{Intruction_Lvl13_PA: 0},
	{TextNumi_Lvl13_PA: 0},
	{TextNuma_Lvl13_PA: 0},
	{HapusBalok_Lvl13_PA: 0},
	{Btn_Next_Lvl13_PA: 0},
	{BtnBalokSatuan_Lvl13_PA: 0},
	{Btn_Play_Lvl13_PA: 0},
	{Bg_Lvl13_PA: 0},
	{Numa_Lvl13_PA: 0},
	{Numi_Lvl13_PA: 0},
	{BalokPuluhan_Lvl13_PA: 0},
	{BtnBalokPuluhan_Lvl13_PA: 0},
	{AngkaText_Lvl13_PA: 0},
	{Angka_Lvl13_PA: 0},
	{AlasPuluhan_Lvl13_PA: 0},
	{AlasSatuan_Lvl13_PA2: 0},
	{gagal_level2_t1: 0},
	{info_level2_t1: 0},
	{berhasil_level2_t1: 0},
	{bentukYangDiterima: 0},
	{kotak_lingkaran_t1: 0},
	{kotak_persegi_t1: 0},
	{kotak_segitiga_t1: 0},
	{belah_ketupat_t1: 0},
	{persegi_panjang_t1: 0},
	{trapesium_t1: 0},
	{jajar_t1: 0},
	{layang_t1: 0},
	{segilima_t1: 0},
	{bentuk: 0},
	{X_origin: 0},
	{Y_origin: 0},
	{ling_bola_level2_t1: 0},
	{ling_cermin_level2_t1: 0},
	{ling_jam_level2_t1: 0},
	{persegi_buku_level2_t1: 0},
	{persegi_jendela_level2_t1: 0},
	{persegi_whiteboard_level2_t1: 0},
	{segitiga_level2_t1: 0},
	{segitiga_penggariskuning_level2_t1: 0},
	{segitiga_penggarispink_level2_t1: 0},
	{tempat_waktu_level2: 0},
	{bg_level2_t1: 0},
	{full_level2_t1: 0},
	{judul_level2_t1: 0},
	{jikaBenar_level_2_t2: 0},
	{jikaWaktuHabis_level_2_t2: 0},
	{jikaSalahpilih_level_2_t2: 0},
	{finish_level_2_t2: 0},
	{motivasi_level_2_t2: 0},
	{isCorrect: 0},
	{bener_level_2_t2: 0},
	{salah2_level_2_t2: 0},
	{salah3_level_2_t2: 0},
	{soal_persegi_level_2_t2: 0},
	{dialog_level_2_t2_2: 0},
	{dialog_level_2_t2_1: 0},
	{PETUNJUKPERSEGI_level_2_t2: 0},
	{tempat_waktu_level3: 0},
	{bg_level_2_t2: 0},
	{componentType: 0},
	{X_target: 0},
	{Y_target: 0},
	{isPlaced: 0},
	{layang_level_2_t3: 0},
	{jendela_level_2_t3: 0},
	{pintu_level_2_t3: 0},
	{atas_stiga_level_2_t3: 0},
	{polygon_level_2_t3: 0},
	{atap_pg_level_2_t3: 0},
	{tangga_level_2_t3: 0},
	{kunci_level_2_t3: 0},
	{dinding_level_2_t3: 0},
	{tap2_sering_level_2_t3: 0},
	{berhasil_level_2_t3: 0},
	{benar_level_2_t3: 0},
	{cobalagi_level_2_t3: 0},
	{numa_level_2_t3: 0},
	{numi_level_2_t3: 0},
	{target_level_2_t3: 0},
	{target_level_2_t3_selesai: 0},
	{tempat_waktu_level2_t3: 0},
	{dialog_level_2_t3: 0},
	{rumahselesaidisusun_level_2_t3: 0},
	{bghitam_level_2_t3: 0},
	{bg_level_2_t3: 0},
	{judul_level_2_t3: 0},
	{dialog_level_2_t4: 0},
	{Fade: 0},
	{finish_level_2_t4: 0},
	{motivasi_level_2_t4: 0},
	{jikaBenar_level_2_t4: 0},
	{jikaSalah_level_2_t4: 0},
	{correctAnswer: 0},
	{screen: 0},
	{screenpage1_level_2_t4: 0},
	{screenpage2_level_2_t4: 0},
	{screenpage3_level_2_t4: 0},
	{screenpage4_level_2_t4: 0},
	{screenpage5_level_2_t4: 0},
	{screenpage6_level_2_t4: 0},
	{screenpage7_level_2_t4: 0},
	{screenpage8_level_2_t4: 0},
	{direction: 0},
	{belakang_level_2_t4: 0},
	{depan_level_2_t4: 0},
	{kanan_level_2_t4: 0},
	{kiri_level_2_t4: 0},
	{screenview: 0},
	{tempat_waktu_level4: 0},
	{bg_level2_t5: 0},
	{bg_item_level_t5: 0},
	{bg_target_level2_t5: 0},
	{item_1_level2_t5: 0},
	{item_2_level2_t5: 0},
	{item_3_level2_t5: 0},
	{soal_level2_t5: 0},
	{target_1_level2_t5: 0},
	{target_2_level2_t5: 0},
	{target_3_level2_t5: 0},
	{tempat_waktu_level2_t5: 0},
	{finish: 0},
	{jikasalah: 0},
	{petunjuk: 0},
	{motivasi: 0},
	{hasil_akhir_t5: 0},
	{bg_level3_t1: 0},
	{Frame_Gajah: 0},
	{Frame_capybara: 0},
	{Frame_rabbit: 0},
	{Plate: 0},
	{IsLocked: 0},
	{Rabbit: 0},
	{Capybara: 0},
	{Gajah: 0},
	{Notif1: 0},
	{background: 0},
	{babi: 0},
	{instruksi: 0},
	{kadal: 0},
	{kelinci: 0},
	{kucing: 0},
	{kurakura: 0},
	{monyet: 0},
	{numaT2: 0},
	{numiT2: 0},
	{referensi2: 0},
	{BabiB2: 0},
	{anjingLaut: 0},
	{flaminggo: 0},
	{Kurakurab2: 0},
	{jerapah: 0},
	{unta: 0},
	{teksKakiPanjang: 0},
	{TeksKakiPendek: 0},
	{Instruksi2: 0},
	{referensi3: 0},
	{singa: 0},
	{SosisKecil: 0},
	{SosisSedang: 0},
	{SosisBesar: 0},
	{Instruksi3: 0},
	{check: 0},
	{check2: 0},
	{check3: 0},
	{wrong: 0},
	{wrong2: 0},
	{wrong3: 0},
	{heart: 0},
	{heartCount: 0},
	{backgroundT3: 0},
	{referensitT31: 0},
	{JerapahBesar: 0},
	{JerapahKecil: 0},
	{instruksiT31: 0},
	{TransparantOverlay: 0},
	{WinNotif: 0},
	{MoveTo: 0},
	{Wipe1: 0},
	{Wipe2: 0},
	{Ready: 0},
	{Retry: 0},
	{PuzzleHolder: 0},
	{BannerTimer: 0},
	{Go: 0},
	{home: 0},
	{LoseNotif: 0},
	{TImer: 0},
	{next: 0},
	{close: 0},
	{pause: 0},
	{Asset_Jeda: 0},
	{Header_Jeda: 0},
	{Resume: 0},
	{home_Pause: 0},
	{Retry_Pause: 0},
	{Layer_Pengenalan_Angka: 0},
	{Target: 0},
	{id_Level_Pengenalan_Angka: 0},
	{Btn_Lvl: 0},
	{Pulau: 0},
	{Bg_Pengenalan_Angka: 0},
	{Awan: 0},
	{Sound: 0},
	{Music: 0},
	{Dev_Info: 0},
	{Achievment: 0},
	{Next_Lay_Roadmap: 0},
	{Header_Reward: 0},
	{Bg_Used: 0},
	{Box: 0},
	{BG_Full_Reward: 0},
	{Reward_Pengenalan_Angka: 0},
	{Reward_PA: 0},
	{InfoPengembang: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{DataReward: 0},
	{Sprite2: 0},
	{level: 0},
	{level2: 0},
	{Sprite4: 0},
	{Fam_Lvl6: 0},
	{Pause_Object: 0},
	{timer: 0},
	{score: 0},
	{currentScreen: 0},
	{totalScreens: 0},
	{correctAnswers: 0},
	{notifShowing: 0},
	{introShown: 0},
	{IsGameOver: 0},
	{TargetAngka: 0},
	{NyawaPengenalanAngka: 0},
	{JarakLompat: 0},
	{KartuPertama_ID: 0},
	{KartuKedua_ID: 0},
	{KartuTerbuka: 0},
	{InputCount: 0},
	{target_Angka: 0},
	{Target_Puluhan: 0},
	{Target_Satuan: 0},
	{Current_Puluhan: 0},
	{Current_Satuan: 0},
	{Level_Pengenalan_Angka: 0},
	{StartTouchY: 0},
	{StartScrollY: 0},
	{RetryToLevel: 0},
	{RoadmapLevel: 0},
	{IsGameOver2: 0},
	{NextLayoutName: 0},
	{timer2: 0},
	{Answer2: 0},
	{framer: 0},
	{stage: 0},
	{cardValue: 0},
	{score2: 0},
	{isPaused: 0},
	{duration: 0},
	{TargetName: 0},
	{LevelLayoutName: 0},
	{Level: 0},
	{retryTo: 0},
	{isMusicOn: 0},
	{isSFXon: 0}
];

self.InstanceType = {
	Awan1: class extends self.ISpriteInstance {},
	Awan2: class extends self.ISpriteInstance {},
	Awan3: class extends self.ISpriteInstance {},
	AwanRumah: class extends self.ISpriteInstance {},
	BG_RoadMap: class extends self.ISpriteInstance {},
	BG_RoadMap2: class extends self.ISpriteInstance {},
	BTN_1: class extends self.ISpriteInstance {},
	BTN_10: class extends self.ISpriteInstance {},
	BTN_11: class extends self.ISpriteInstance {},
	BTN_12: class extends self.ISpriteInstance {},
	BTN_13: class extends self.ISpriteInstance {},
	BTN_14: class extends self.ISpriteInstance {},
	BTN_15: class extends self.ISpriteInstance {},
	BTN_2: class extends self.ISpriteInstance {},
	BTN_3: class extends self.ISpriteInstance {},
	BTN_4: class extends self.ISpriteInstance {},
	BTN_5: class extends self.ISpriteInstance {},
	BTN_6: class extends self.ISpriteInstance {},
	BTN_7: class extends self.ISpriteInstance {},
	BTN_8: class extends self.ISpriteInstance {},
	BTN_9: class extends self.ISpriteInstance {},
	BTN_MusicOff: class extends self.ISpriteInstance {},
	BTN_MusicOn: class extends self.ISpriteInstance {},
	BTN_SoundOff: class extends self.ISpriteInstance {},
	BTN_SoundOn: class extends self.ISpriteInstance {},
	CameraFocus: class extends self.ISpriteInstance {},
	PulauKamarTidur: class extends self.ISpriteInstance {},
	PulauKebunBinatang: class extends self.ISpriteInstance {},
	PulauKelas: class extends self.ISpriteInstance {},
	MainTitle: class extends self.ISpriteInstance {},
	Numa: class extends self.ISpriteInstance {},
	Numi: class extends self.ISpriteInstance {},
	StartButton: class extends self.ISpriteInstance {},
	BG_MainMenu: class extends self.ISpriteInstance {},
	Group: class extends self.ISpriteInstance {},
	Drop: class extends self.ISpriteInstance {},
	Drag: class extends self.ISpriteInstance {},
	Banner: class extends self.ISpriteInstance {},
	Tema_KamarTidurLV1TKB: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Drag_2: class extends self.ISpriteInstance {},
	Drop_2: class extends self.ISpriteInstance {},
	Bg_Lvl1_Open: class extends self.ISpriteInstance {},
	Bg_Level2_T2: class extends self.ISpriteInstance {},
	Drag_Lvl2: class extends self.ISpriteInstance {},
	Bg_Level2_Open: class extends self.ISpriteInstance {},
	Drop_Lvl2: class extends self.ISpriteInstance {},
	Bg_lvl3_Basic_PA: class extends self.ISpriteInstance {},
	Btn_Lvl3_Play: class extends self.ISpriteInstance {},
	Angka_lvl3_PA: class extends self.ISpriteInstance {},
	Bg_Lvl4_Basic_PA: class extends self.ISpriteInstance {},
	Judul_Lvl4_PA: class extends self.ISpriteInstance {},
	Btn_Play_Lvl4_Basic_PA: class extends self.ISpriteInstance {},
	Karakter_Lvl4_Basic_PA: class extends self.ISpriteInstance {},
	Drag_Lvl4_PA: class extends self.ISpriteInstance {},
	Papan_Lvl4_PA: class extends self.ISpriteInstance {},
	Buku_Lvl4_PA: class extends self.ISpriteInstance {},
	Judul_Lvl4_PA_Game: class extends self.ISpriteInstance {},
	Drop_Lvl4_PA: class extends self.ISpriteInstance {},
	LEMARI_lVL4_pa: class extends self.ISpriteInstance {},
	Dialog_Lvl4_PA: class extends self.ISpriteInstance {},
	Drag_Buku_Lvl4_PA: class extends self.ISpriteInstance {},
	Drop_Buku_Lvl4_PA: class extends self.ISpriteInstance {},
	Btn_Back_Lvl4_PA: class extends self.ISpriteInstance {},
	Kartu_Buku_Lvl4_PA: class extends self.ISpriteInstance {},
	DataLevel4_PA: class extends self.IDictionaryInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Bayangan_Lvl4_PA: class extends self.ISpriteInstance {},
	JudulBuku_Lvl4_PA: class extends self.ISpriteInstance {},
	Bg_Lvl5_PA: class extends self.ISpriteInstance {},
	Play_BTN_Lvl5_PA: class extends self.ISpriteInstance {},
	Drag_Lvl5_PA: class extends self.ISpriteInstance {},
	Dialog_Lvl5_PA: class extends self.ISpriteInstance {},
	Lanjut_Lvl5_PA: class extends self.ISpriteInstance {},
	Header_Lvl5_PA: class extends self.ISpriteInstance {},
	Drop_Lvl5_PA: class extends self.ISpriteInstance {},
	Btb_Play_Lvl7: class extends self.ISpriteInstance {},
	Group3: class extends self.ISpriteInstance {},
	bebek_lvl7: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BTN_Play_Lvl7: class extends self.ISpriteInstance {},
	aNGKA_Lvl7_PA: class extends self.ISpriteInstance {},
	Drag_Bubble_Lvl8_PA: class extends self.ISpriteInstance {},
	Bg_Lvl8_PA: class extends self.ISpriteInstance {},
	Asset_Lvl8_PA: class extends self.ISpriteInstance {},
	Btn_Play_Lvl8_PA: class extends self.ISpriteInstance {},
	Drop_Bubble_Lvl8_PA: class extends self.ISpriteInstance {},
	checklist_lvl9_PA: class extends self.ISpriteInstance {},
	bebek_lvl9_PA: class extends self.ISpriteInstance {},
	Text_Lvl9_PA: class extends self.ISpriteInstance {},
	BubbleClr_Lvl9_PA: class extends self.ISpriteInstance {},
	Bubble_Lvl9_PA: class extends self.ISpriteInstance {},
	Number_Level9_PA: class extends self.ISpriteInstance {},
	bg_Lvl9_PA: class extends self.ISpriteInstance {},
	bgfull_Lvl9_PA: class extends self.ISpriteInstance {},
	bgfix_Lvl9_PA: class extends self.ISpriteInstance {},
	BtnPlay_Lvl9_PA: class extends self.ISpriteInstance {},
	Bg_Lvl10_PA: class extends self.ISpriteInstance {},
	Btn_Play_Lvl10: class extends self.ISpriteInstance {},
	DragSabun_Lvl10_PA: class extends self.ISpriteInstance {},
	DropSabun_Lvl10_PA: class extends self.ISpriteInstance {},
	Bg_Lvl6_PA: class extends self.ISpriteInstance {},
	Btn_Play_Lvl6_PA: class extends self.ISpriteInstance {},
	Lantai_Lvl6_PA: class extends self.ISpriteInstance {},
	LantaiBenar_Lvl6_PA: class extends self.ISpriteInstance {},
	Numi_Lvl6_PA: class extends self.ISpriteInstance {},
	Nyawa_Lvl6_PA: class extends self.ISpriteInstance {},
	NyawaText_Lvl6_PA: class extends self.ITextInstance {},
	Bg_Lvl14_PA: class extends self.ISpriteInstance {},
	Drag_Card_Lvl14_PA: class extends self.ISpriteInstance {},
	Btn_Play_Lvl14_Pa: class extends self.ISpriteInstance {},
	Btn_Next_Lvl14_PA: class extends self.ISpriteInstance {},
	Drop_Card_Lvl14_PA2: class extends self.ISpriteInstance {},
	Asset_Lvl11: class extends self.ISpriteInstance {},
	BG_Lvl11: class extends self.ISpriteInstance {},
	Btn_Play_Lvl11_PA: class extends self.ISpriteInstance {},
	Card_Lvl11_PA: class extends self.ISpriteInstance {},
	Text_Lvl11: class extends self.ISpriteInstance {},
	Btn_Next_Lvl15_PA: class extends self.ISpriteInstance {},
	Card_Lvl15_PA: class extends self.ISpriteInstance {},
	Bg_Lvl15_PA: class extends self.ISpriteInstance {},
	Asset_Lvl15_PA: class extends self.ISpriteInstance {},
	Btn_Play_Lvl15_PA: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	ShowCard_Lvl15_PA2: class extends self.ISpriteInstance {},
	NextShowCard_Lvl15_PA3: class extends self.ISpriteInstance {},
	Karakter_Lvl15_PA: class extends self.ISpriteInstance {},
	Text_Finish_Lvl15PA: class extends self.ISpriteInstance {},
	Chanel_Lvl12_PA: class extends self.ISpriteInstance {},
	Btn_Play_Lvl12_PA: class extends self.ISpriteInstance {},
	AngkaRemote_Lvl12_PA: class extends self.ISpriteInstance {},
	ChatNumi_Lvl12_PA: class extends self.ISpriteInstance {},
	ChatNuma_Lvl12_PA: class extends self.ISpriteInstance {},
	Asset_Lvl12_PA: class extends self.ISpriteInstance {},
	Bg_Lvl12_PA: class extends self.ISpriteInstance {},
	TextPuluhan_Lvl12_PA: class extends self.ITextInstance {},
	TextSatuan_Lvl12_PA: class extends self.ITextInstance {},
	AngkaAcak: class extends self.IArrayInstance {},
	anima: class extends self.ISpriteInstance {},
	UntitledDesign: class extends self.ISpriteInstance {},
	Lanjut_Lvl12_PA: class extends self.ISpriteInstance {},
	BalokSatuan_Lvl13_PA: class extends self.ISpriteInstance {},
	Intruction_Lvl13_PA: class extends self.ISpriteInstance {},
	TextNumi_Lvl13_PA: class extends self.ISpriteInstance {},
	TextNuma_Lvl13_PA: class extends self.ISpriteInstance {},
	HapusBalok_Lvl13_PA: class extends self.ISpriteInstance {},
	Btn_Next_Lvl13_PA: class extends self.ISpriteInstance {},
	BtnBalokSatuan_Lvl13_PA: class extends self.ISpriteInstance {},
	Btn_Play_Lvl13_PA: class extends self.ISpriteInstance {},
	Bg_Lvl13_PA: class extends self.ISpriteInstance {},
	Numa_Lvl13_PA: class extends self.ISpriteInstance {},
	Numi_Lvl13_PA: class extends self.ISpriteInstance {},
	BalokPuluhan_Lvl13_PA: class extends self.ISpriteInstance {},
	BtnBalokPuluhan_Lvl13_PA: class extends self.ISpriteInstance {},
	AngkaText_Lvl13_PA: class extends self.ISpriteInstance {},
	Angka_Lvl13_PA: class extends self.ISpriteInstance {},
	AlasPuluhan_Lvl13_PA: class extends self.ISpriteInstance {},
	AlasSatuan_Lvl13_PA2: class extends self.ISpriteInstance {},
	gagal_level2_t1: class extends self.ISpriteInstance {},
	info_level2_t1: class extends self.ISpriteInstance {},
	berhasil_level2_t1: class extends self.ISpriteInstance {},
	kotak_lingkaran_t1: class extends self.ISpriteInstance {},
	kotak_persegi_t1: class extends self.ISpriteInstance {},
	kotak_segitiga_t1: class extends self.ISpriteInstance {},
	belah_ketupat_t1: class extends self.ISpriteInstance {},
	persegi_panjang_t1: class extends self.ISpriteInstance {},
	trapesium_t1: class extends self.ISpriteInstance {},
	jajar_t1: class extends self.ISpriteInstance {},
	layang_t1: class extends self.ISpriteInstance {},
	segilima_t1: class extends self.ISpriteInstance {},
	ling_bola_level2_t1: class extends self.ISpriteInstance {},
	ling_cermin_level2_t1: class extends self.ISpriteInstance {},
	ling_jam_level2_t1: class extends self.ISpriteInstance {},
	persegi_buku_level2_t1: class extends self.ISpriteInstance {},
	persegi_jendela_level2_t1: class extends self.ISpriteInstance {},
	persegi_whiteboard_level2_t1: class extends self.ISpriteInstance {},
	segitiga_level2_t1: class extends self.ISpriteInstance {},
	segitiga_penggariskuning_level2_t1: class extends self.ISpriteInstance {},
	segitiga_penggarispink_level2_t1: class extends self.ISpriteInstance {},
	tempat_waktu_level2: class extends self.ISpriteInstance {},
	bg_level2_t1: class extends self.ISpriteInstance {},
	full_level2_t1: class extends self.ISpriteInstance {},
	judul_level2_t1: class extends self.ISpriteInstance {},
	jikaBenar_level_2_t2: class extends self.ISpriteInstance {},
	jikaWaktuHabis_level_2_t2: class extends self.ISpriteInstance {},
	jikaSalahpilih_level_2_t2: class extends self.ISpriteInstance {},
	finish_level_2_t2: class extends self.ISpriteInstance {},
	motivasi_level_2_t2: class extends self.ISpriteInstance {},
	bener_level_2_t2: class extends self.ISpriteInstance {},
	salah2_level_2_t2: class extends self.ISpriteInstance {},
	salah3_level_2_t2: class extends self.ISpriteInstance {},
	soal_persegi_level_2_t2: class extends self.ISpriteInstance {},
	dialog_level_2_t2_2: class extends self.ISpriteInstance {},
	dialog_level_2_t2_1: class extends self.ISpriteInstance {},
	PETUNJUKPERSEGI_level_2_t2: class extends self.ISpriteInstance {},
	tempat_waktu_level3: class extends self.ISpriteInstance {},
	bg_level_2_t2: class extends self.ISpriteInstance {},
	layang_level_2_t3: class extends self.ISpriteInstance {},
	jendela_level_2_t3: class extends self.ISpriteInstance {},
	pintu_level_2_t3: class extends self.ISpriteInstance {},
	atas_stiga_level_2_t3: class extends self.ISpriteInstance {},
	polygon_level_2_t3: class extends self.ISpriteInstance {},
	atap_pg_level_2_t3: class extends self.ISpriteInstance {},
	tangga_level_2_t3: class extends self.ISpriteInstance {},
	kunci_level_2_t3: class extends self.ISpriteInstance {},
	dinding_level_2_t3: class extends self.ISpriteInstance {},
	tap2_sering_level_2_t3: class extends self.ISpriteInstance {},
	berhasil_level_2_t3: class extends self.ISpriteInstance {},
	benar_level_2_t3: class extends self.ISpriteInstance {},
	cobalagi_level_2_t3: class extends self.ISpriteInstance {},
	numa_level_2_t3: class extends self.ISpriteInstance {},
	numi_level_2_t3: class extends self.ISpriteInstance {},
	target_level_2_t3: class extends self.ISpriteInstance {},
	target_level_2_t3_selesai: class extends self.ISpriteInstance {},
	tempat_waktu_level2_t3: class extends self.ISpriteInstance {},
	dialog_level_2_t3: class extends self.ISpriteInstance {},
	rumahselesaidisusun_level_2_t3: class extends self.ISpriteInstance {},
	bghitam_level_2_t3: class extends self.ISpriteInstance {},
	bg_level_2_t3: class extends self.ISpriteInstance {},
	judul_level_2_t3: class extends self.ISpriteInstance {},
	dialog_level_2_t4: class extends self.ISpriteInstance {},
	finish_level_2_t4: class extends self.ISpriteInstance {},
	motivasi_level_2_t4: class extends self.ISpriteInstance {},
	jikaBenar_level_2_t4: class extends self.ISpriteInstance {},
	jikaSalah_level_2_t4: class extends self.ISpriteInstance {},
	screenpage1_level_2_t4: class extends self.ISpriteInstance {},
	screenpage2_level_2_t4: class extends self.ISpriteInstance {},
	screenpage3_level_2_t4: class extends self.ISpriteInstance {},
	screenpage4_level_2_t4: class extends self.ISpriteInstance {},
	screenpage5_level_2_t4: class extends self.ISpriteInstance {},
	screenpage6_level_2_t4: class extends self.ISpriteInstance {},
	screenpage7_level_2_t4: class extends self.ISpriteInstance {},
	screenpage8_level_2_t4: class extends self.ISpriteInstance {},
	belakang_level_2_t4: class extends self.ISpriteInstance {},
	depan_level_2_t4: class extends self.ISpriteInstance {},
	kanan_level_2_t4: class extends self.ISpriteInstance {},
	kiri_level_2_t4: class extends self.ISpriteInstance {},
	screenview: class extends self.ITextInstance {},
	tempat_waktu_level4: class extends self.ISpriteInstance {},
	bg_level2_t5: class extends self.ISpriteInstance {},
	bg_item_level_t5: class extends self.ISpriteInstance {},
	bg_target_level2_t5: class extends self.ISpriteInstance {},
	item_1_level2_t5: class extends self.ISpriteInstance {},
	item_2_level2_t5: class extends self.ISpriteInstance {},
	item_3_level2_t5: class extends self.ISpriteInstance {},
	soal_level2_t5: class extends self.ISpriteInstance {},
	target_1_level2_t5: class extends self.ISpriteInstance {},
	target_2_level2_t5: class extends self.ISpriteInstance {},
	target_3_level2_t5: class extends self.ISpriteInstance {},
	tempat_waktu_level2_t5: class extends self.ISpriteInstance {},
	finish: class extends self.ISpriteInstance {},
	jikasalah: class extends self.ISpriteInstance {},
	petunjuk: class extends self.ISpriteInstance {},
	motivasi: class extends self.ISpriteInstance {},
	hasil_akhir_t5: class extends self.ISpriteInstance {},
	bg_level3_t1: class extends self.ISpriteInstance {},
	Frame_Gajah: class extends self.ISpriteInstance {},
	Frame_capybara: class extends self.ISpriteInstance {},
	Frame_rabbit: class extends self.ISpriteInstance {},
	Plate: class extends self.ISpriteInstance {},
	Rabbit: class extends self.ISpriteInstance {},
	Capybara: class extends self.ISpriteInstance {},
	Gajah: class extends self.ISpriteInstance {},
	Notif1: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	babi: class extends self.ISpriteInstance {},
	instruksi: class extends self.ISpriteInstance {},
	kadal: class extends self.ISpriteInstance {},
	kelinci: class extends self.ISpriteInstance {},
	kucing: class extends self.ISpriteInstance {},
	kurakura: class extends self.ISpriteInstance {},
	monyet: class extends self.ISpriteInstance {},
	numaT2: class extends self.ISpriteInstance {},
	numiT2: class extends self.ISpriteInstance {},
	referensi2: class extends self.ISpriteInstance {},
	BabiB2: class extends self.ISpriteInstance {},
	anjingLaut: class extends self.ISpriteInstance {},
	flaminggo: class extends self.ISpriteInstance {},
	Kurakurab2: class extends self.ISpriteInstance {},
	jerapah: class extends self.ISpriteInstance {},
	unta: class extends self.ISpriteInstance {},
	teksKakiPanjang: class extends self.ISpriteInstance {},
	TeksKakiPendek: class extends self.ISpriteInstance {},
	Instruksi2: class extends self.ISpriteInstance {},
	referensi3: class extends self.ISpriteInstance {},
	singa: class extends self.ISpriteInstance {},
	SosisKecil: class extends self.ISpriteInstance {},
	SosisSedang: class extends self.ISpriteInstance {},
	SosisBesar: class extends self.ISpriteInstance {},
	Instruksi3: class extends self.ISpriteInstance {},
	check: class extends self.ISpriteInstance {},
	check2: class extends self.ISpriteInstance {},
	check3: class extends self.ISpriteInstance {},
	wrong: class extends self.ISpriteInstance {},
	wrong2: class extends self.ISpriteInstance {},
	wrong3: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	heartCount: class extends self.ITextInstance {},
	backgroundT3: class extends self.ISpriteInstance {},
	referensitT31: class extends self.ISpriteInstance {},
	JerapahBesar: class extends self.ISpriteInstance {},
	JerapahKecil: class extends self.ISpriteInstance {},
	instruksiT31: class extends self.ISpriteInstance {},
	TransparantOverlay: class extends self.ISpriteInstance {},
	WinNotif: class extends self.ISpriteInstance {},
	Wipe1: class extends self.ISpriteInstance {},
	Wipe2: class extends self.ISpriteInstance {},
	Ready: class extends self.ISpriteInstance {},
	Retry: class extends self.ISpriteInstance {},
	PuzzleHolder: class extends self.ISpriteInstance {},
	BannerTimer: class extends self.ISpriteInstance {},
	Go: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	LoseNotif: class extends self.ISpriteInstance {},
	TImer: class extends self.ITextInstance {},
	next: class extends self.ISpriteInstance {},
	close: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	Asset_Jeda: class extends self.ISpriteInstance {},
	Header_Jeda: class extends self.ISpriteInstance {},
	Resume: class extends self.ISpriteInstance {},
	home_Pause: class extends self.ISpriteInstance {},
	Retry_Pause: class extends self.ISpriteInstance {},
	Layer_Pengenalan_Angka: class extends self.ISpriteInstance {},
	Btn_Lvl: class extends self.ISpriteInstance {},
	Pulau: class extends self.ISpriteInstance {},
	Bg_Pengenalan_Angka: class extends self.ISpriteInstance {},
	Awan: class extends self.ISpriteInstance {},
	Sound: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	Dev_Info: class extends self.ISpriteInstance {},
	Achievment: class extends self.ISpriteInstance {},
	Next_Lay_Roadmap: class extends self.ISpriteInstance {},
	Header_Reward: class extends self.ISpriteInstance {},
	Bg_Used: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	BG_Full_Reward: class extends self.ISpriteInstance {},
	Reward_PA: class extends self.ISpriteInstance {},
	InfoPengembang: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	DataReward: class extends self.IDictionaryInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	level: class extends self.ISVGPictureInstance {},
	level2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Fam_Lvl6: class extends self.ISpriteInstance {},
	Pause_Object: class extends self.ISpriteInstance {}
}